### ISSUE TITLE
Add frequency-based aesthetics to the overview map

### ISSUE THREAD

**Issue by stupidpupil** [stupidpupil/parochial#12]

**Comment by stupidpupil** [comment]
What I'd really like is some sort of Carto?CSS-like setup:
```css

trip[operator="Transport for Wales"]{
  color: red;
}

station.heavy_rail{
  color: red;
  size: 5;
}

```

??
